### ISSUE TITLE
index pagina ophalen

### ISSUE THREAD

**Issue by Fabienne02** [KaivWezel/cmda-mid-term#19]

**Comment by bommezijn** [comment]
Index wordt opgehaald maar is niet dynamisch, linkjes werken nog niet. laat ook de header zien terwijl je dat eigenlijk niet wilt.

- [ ] Fix URLs 
- [ ] Fix header weergave op index

**Comment by bommezijn** [comment]
![CleanShot 2022-06-22 at 11 22 02@2x](https://user-images.githubusercontent.com/13199349/174993579-5f98d15f-f2f1-4587-b965-ec7b8b71b83d.png)
