### ISSUE TITLE
Margin-top on IndexContainer can be removed or set to navigation height

### ISSUE THREAD

**Issue by KaivWezel** [KaivWezel/cmda-mid-term#35]

**Comment by KaivWezel** [comment]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/66356377/174979072-2fda07da-7ab9-4db0-ae2b-2337872ac9f0.png">
***

Veel te veel margin

**Comment by bommezijn** [comment]
Dit heeft betrekking met de heroComponent van ieder standaard. Indien deze margin er niet in zit wordt de content verborgen. Dit heeft te maken met dat een slice niet op een normale manier buiten de slice-zone aangeroepen kan worden. Hierom heeft de Hero component een `position: absolute`
![CleanShot 2022-06-22 at 12 08 05@2x](https://user-images.githubusercontent.com/13199349/175003636-f48ccd0f-5246-43b4-9737-328ff0d2be69.png)
